export default [

    {
        "hotelId": "1", //酒店ID
        "hotelName": "兴基伯尔曼酒店(荣东三路店)",
        "imgUrl": "xingjiboerman.jpeg",
        "minPrice": "88.88",
        "roomType": "小时+时段+全日",
        "hotelAttribute": "宠物携带,台球室,卡拉OK,叫车服务,租车服务,美容美发",
        "hours": "48",
        "distance": "237.0",
        "programme": "1",
        "cityName": "北京",
        "starLevel": "4",
        "earlyDeparture": "1",
        "maxPeople": "2",
        "decorationTime": "2019",
        "startTime": "2013",
        "characteristic": "房间干净整洁，提供早餐",
        "introduce": "服务周到，干净卫生",
        "floorHeight": "10",
        "storeyHeight": "17",
        "roomNum": "78",
        "lngs": "116.518035",
        "lats": "39.796146",
        "tradingArea": "亦庄地区|欢乐谷游乐区",
        "recommendText":"酒店坐落于亦庄新城附近,上五环不到五分钟，酒店环境秀丽，空气清新免费的早餐",
        "firmScore":'4.7',
        "commentNum":"2453",
        "imgarry":['xingjiboerman.jpeg','xingjiboerman1.jpg','xingjiboerman2.jpeg'],
        "array":[
            {
                "hotelId": "1",
                "roomId": "1",
                "roomName": "豪华单人间",
                "bedNumber": 1,
                "bedModel": 1,
                "roomAreaBegan": "105.22",
                "roomAreaEnd": "106.88",
                "floorNum": "9",
                "isWindow": "1",
                "aloneWc": "1",
                "roomPrice": 17,
                "roomImgUrl": "",
                "accType": "小时,时段,全日",
                "depositType": 3,
                "attrs": "独立卫生间,洗漱用品,淋浴,24小时热水,吹风机,wifi,空气净化器,台式电脑,电话,热水壶,空调,电视(卫星频道)",
                "roomScore": 4.0,
                "inDay": 0,
                "inHours": 2.0,
                "describe": "多时推荐2.0小时时段房*3.7= ¥7.40",
                "traditionDescribe": "传统入住方案1晚:1*88.88=¥88.88",
                "originalPrice": 88.88,
                "presentPrice": 7.40,
                "discount": 81.48,
                "imgUrl": 'xingjiboerman.jpeg',
            },{
                "hotelId": "1",
                "roomId": "2",
                "roomName": "豪华双人间",
                "bedNumber": 1,
                "bedModel": 1,
                "roomAreaBegan": "105.22",
                "roomAreaEnd": "106.88",
                "floorNum": "9",
                "isWindow": "1",
                "aloneWc": "1",
                "roomPrice": 18,
                "roomImgUrl": "",
                "accType": "小时,时段,全日",
                "depositType": 3,
                "attrs": "独立卫生间,洗漱用品,淋浴,24小时热水,吹风机,wifi,空气净化器,台式电脑,电话,热水壶,空调,电视(卫星频道)",
                "roomScore": 4.0,
                "inDay": 0,
                "inHours": 2.0,
                "describe": "多时推荐2.0小时时段房*3.7= ¥7.40",
                "traditionDescribe": "传统入住方案1晚:1*88.88=¥88.88",
                "originalPrice": 88.88,
                "presentPrice": 7.40,
                "discount": 81.48,
                "imgUrl": 'xingjiboerman1.jpg',
            },{
                "hotelId": "1",
                "roomId": "3",
                "roomName": "三人床",
                "bedNumber": 1,
                "bedModel": 1,
                "roomAreaBegan": "105.22",
                "roomAreaEnd": "106.88",
                "floorNum": "9",
                "isWindow": "1",
                "aloneWc": "1",
                "roomPrice": 19,
                "roomImgUrl": "",
                "accType": "小时,时段,全日",
                "depositType": 3,
                "attrs": "独立卫生间,洗漱用品,淋浴,24小时热水,吹风机,wifi,空气净化器,台式电脑,电话,热水壶,空调,电视(卫星频道)",
                "roomScore": 4.0,
                "inDay": 0,
                "inHours": 2.0,
                "describe": "多时推荐2.0小时时段房*3.7= ¥7.40",
                "traditionDescribe": "传统入住方案1晚:1*88.88=¥88.88",
                "originalPrice": 88.88,
                "presentPrice": 7.40,
                "discount": 81.48,
                "imgUrl": 'xingjiboerman2.jpeg',
            },

        ],
    },
    {
        "hotelId": "2",
        "hotelName": "汉庭连锁酒店(北京蒲黄榆店)",
        "imgUrl": "hanting.jpeg",
        "minPrice": "88.88",
        "roomType": "小时+时段+全日",
        "hotelAttribute": "美容美发,旅游服务,残疾人设施,电子游戏室,乒乓球室,看护小孩服务,行李寄存",
        "hours": "48",
        "distance": "11301.0",
        "programme": "1",
        "cityName": "北京",
        "starLevel": "3",
        "earlyDeparture": "1",
        "maxPeople": "2",
        "decorationTime": "2019",
        "startTime": "2012",
        "characteristic": "房间干净整洁，提供早餐",
        "introduce": "服务周到，干净卫生",
        "floorHeight": "15",
        "storeyHeight": "9",
        "roomNum": "81",
        "lngs": "116.42953",
        "lats": "39.872655",
        "tradingArea": "崇文门|劲松、潘家园地区",
        "recommendText":"酒店坐落于蒲黄榆附近,距离三里屯，天安门不到半小时车程，附近就有小吃一条街",
        "firmScore":'4.8',
        "commentNum":"7892",
        "imgarry":['hanting.jpeg','hanting1.jpeg','hanting2.jpeg','hanting3.jpeg'],
        "array":[
            {
                "hotelId": "2",
                "roomId": "1",
                "roomName": "豪华单人间",
                "bedNumber": 1,
                "bedModel": 1,
                "roomAreaBegan": "105.22",
                "roomAreaEnd": "106.88",
                "floorNum": "9",
                "isWindow": "1",
                "aloneWc": "1",
                "roomPrice": 10,
                "roomImgUrl": "",
                "accType": "小时,时段,全日",
                "depositType": 3,
                "attrs": "独立卫生间,洗漱用品,淋浴,24小时热水,吹风机,wifi,空气净化器,台式电脑,电话,热水壶,空调,电视(卫星频道)",
                "roomScore": 4.0,
                "inDay": 0,
                "inHours": 2.0,
                "describe": "多时推荐2.0小时时段房*3.7= ¥7.40",
                "traditionDescribe": "传统入住方案1晚:1*88.88=¥88.88",
                "originalPrice": 88.88,
                "presentPrice": 7.40,
                "discount": 81.48,
                "imgUrl": "hanting1.jpeg"
            },{
                "hotelId": "2",
                "roomId": "2",
                "roomName": "豪华双人间",
                "bedNumber": 1,
                "bedModel": 1,
                "roomAreaBegan": "105.22",
                "roomAreaEnd": "106.88",
                "floorNum": "9",
                "isWindow": "1",
                "aloneWc": "1",
                "roomPrice": 12,
                "roomImgUrl": "",
                "accType": "小时,时段,全日",
                "depositType": 3,
                "attrs": "独立卫生间,洗漱用品,淋浴,24小时热水,吹风机,wifi,空气净化器,台式电脑,电话,热水壶,空调,电视(卫星频道)",
                "roomScore": 4.0,
                "inDay": 0,
                "inHours": 2.0,
                "describe": "多时推荐2.0小时时段房*3.7= ¥7.40",
                "traditionDescribe": "传统入住方案1晚:1*88.88=¥88.88",
                "originalPrice": 88.88,
                "presentPrice": 7.40,
                "discount": 81.48,
                "imgUrl": "hanting2.jpeg"
            },{
                "hotelId": "2",
                " c": "3",
                "roomName": "三人床",
                "bedNumber": 1,
                "bedModel": 1,
                "roomAreaBegan": "105.22",
                "roomAreaEnd": "106.88",
                "floorNum": "9",
                "isWindow": "1",
                "aloneWc": "1",
                "roomPrice": 13,
                "roomImgUrl": "",
                "accType": "小时,时段,全日",
                "depositType": 3,
                "attrs": "独立卫生间,洗漱用品,淋浴,24小时热水,吹风机,wifi,空气净化器,台式电脑,电话,热水壶,空调,电视(卫星频道)",
                "roomScore": 4.0,
                "inDay": 0,
                "inHours": 2.0,
                "describe": "多时推荐2.0小时时段房*3.7= ¥7.40",
                "traditionDescribe": "传统入住方案1晚:1*88.88=¥88.88",
                "originalPrice": 88.88,
                "presentPrice": 7.40,
                "discount": 81.48,
                "imgUrl": "hanting3.jpeg"
            },

        ]
    },
    {
        "hotelId": "3",
        "hotelName": "如家连锁酒店(北京蒲黄榆店)",
        "imgUrl": "rujia.jpeg",
        "minPrice": "88.88",
        "roomType": "小时+时段+全日",
        "hotelAttribute": "美容美发,旅游服务,残疾人设施,电子游戏室,乒乓球室,看护小孩服务,行李寄存",
        "hours": "48",
        "distance": "11301.0",
        "programme": "1",
        "cityName": "北京",
        "starLevel": "2",
        "earlyDeparture": "1",
        "maxPeople": "2",
        "decorationTime": "2016",
        "startTime": "2011",
        "characteristic": "房间干净整洁，提供早餐",
        "introduce": "服务周到，干净卫生",
        "floorHeight": "15",
        "storeyHeight": "3",
        "roomNum": "81",
        "lngs": "116.42953",
        "lats": "39.872655",
        "tradingArea": "崇文门|劲松、潘家园地区",
        "recommendText":"酒店坐落于宋家庄附近，周围距离潘家园古玩城非常近，人文气息浓厚",
        "commentNum":"6179",
        "firmScore":'4.9',
        "imgarry":['rujia.jpeg','rujia1.jpeg','rujia2.jpeg','rujia3.jpeg'],
        "array":[
            {
                "hotelId": "3",
                "roomId": "1",
                "roomName": "豪华单人间",
                "bedNumber": 1,
                "bedModel": 1,
                "roomAreaBegan": "105.22",
                "roomAreaEnd": "106.88",
                "floorNum": "9",
                "isWindow": "1",
                "aloneWc": "1",
                "roomPrice": 14,
                "roomImgUrl": "",
                "accType": "小时,时段,全日",
                "depositType": 3,
                "attrs": "独立卫生间,洗漱用品,淋浴,24小时热水,吹风机,wifi,空气净化器,台式电脑,电话,热水壶,空调,电视(卫星频道)",
                "roomScore": 4.0,
                "inDay": 0,
                "inHours": 2.0,
                "describe": "多时推荐2.0小时时段房*3.7= ¥7.40",
                "traditionDescribe": "传统入住方案1晚:1*88.88=¥88.88",
                "originalPrice": 88.88,
                "presentPrice": 7.40,
                "discount": 81.48,
                "imgUrl": "rujia1.jpeg"
            },{
                "hotelId": "3",
                "roomId": "2",
                "roomName": "豪华双人间",
                "bedNumber": 1,
                "bedModel": 1,
                "roomAreaBegan": "105.22",
                "roomAreaEnd": "106.88",
                "floorNum": "9",
                "isWindow": "1",
                "aloneWc": "1",
                "roomPrice": 15,
                "roomImgUrl": "",
                "accType": "小时,时段,全日",
                "depositType": 3,
                "attrs": "独立卫生间,洗漱用品,淋浴,24小时热水,吹风机,wifi,空气净化器,台式电脑,电话,热水壶,空调,电视(卫星频道)",
                "roomScore": 4.0,
                "inDay": 0,
                "inHours": 2.0,
                "describe": "多时推荐2.0小时时段房*3.7= ¥7.40",
                "traditionDescribe": "传统入住方案1晚:1*88.88=¥88.88",
                "originalPrice": 88.88,
                "presentPrice": 7.40,
                "discount": 81.48,
                "imgUrl": "rujia2.jpeg"
            },{
                "hotelId": "3",
                "roomId": "3",
                "roomName": "三人床",
                "bedNumber": 1,
                "bedModel": 1,
                "roomAreaBegan": "105.22",
                "roomAreaEnd": "106.88",
                "floorNum": "9",
                "isWindow": "1",
                "aloneWc": "1",
                "roomPrice": 16,
                "roomImgUrl": "",
                "accType": "小时,时段,全日",
                "depositType": 3,
                "attrs": "独立卫生间,洗漱用品,淋浴,24小时热水,吹风机,wifi,空气净化器,台式电脑,电话,热水壶,空调,电视(卫星频道)",
                "roomScore": 4.0,
                "inDay": 0,
                "inHours": 2.0,
                "describe": "多时推荐2.0小时时段房*3.7= ¥7.40",
                "traditionDescribe": "传统入住方案1晚:1*88.88=¥88.88",
                "originalPrice": 88.88,
                "presentPrice": 7.40,
                "discount": 81.48,
                "imgUrl": "rujia3.jpeg"
            },

        ]
    }
           
]